version: 2.1

jobs:
  plan:
    parameters:
      plan_filepath:
        type: string
    executor: cimg-base
    steps:
      - checkout
      - run: echo "terraform plan -out << parameters.plan_filepath >>"
  