version: 2.1

orbs:
  pf: circleci/path-filtering@1.0.0
  cli: circleci/circleci-cli@0.1.9

commands:
  validate_config:
    parameters:
      config_file:
        type: string
        default: /tmp/generated-config.yml
    steps:
      - run:
          name: Validate config
          command: circleci config validate << parameters.config_file >>
          when: always
  debug_error:
    steps:
      - run:
          name: debug yq
          when: always
          command: |
            yq eval-all '. as $item ireduce ({}; . * $item )'  ./.circleci/foobar.yml
      - run:
          # See https://mikefarah.gitbook.io/yq/operators/anchor-and-alias-operators#explode-with-merge-anchors
          name: show fix with explode
          when: always
          command: |
            yq eval-all '. as $item ireduce ({}; . * $item ) | explode(.)'  ./.circleci/foobar.yml


jobs:
  setup:
    executor: pf/default
    steps:
      - cli/install
      - checkout
      - pf/set-parameters:
          base-revision: main
          mapping: |
            .* foobar true .circleci/foobar.yml
      - pf/generate-config
      - validate_config
      - debug_error
      - validate_config
workflows:
  setup:
    jobs:
      - setup