version: 2.1

# -- <alias>

tag_filter: &tag_filter
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /.*/

## -- </alias>

# define the parameters from the setup config.
parameters:
  foobar:
    type: boolean
    default: false

executors:
  cimg-base:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  plan:
    parameters:
      plan_filepath:
        type: string
    executor: cimg-base
    steps:
      - checkout
      - run: echo "terraform plan -out << parameters.plan_filepath >>"

workflows:
  foobar:
    when: << pipeline.parameters.foobar >>
    jobs:
      - plan:
          plan_filepath: 'main.tfplan'
      - hold:
          <<: *tag_filter
          type: approval
          requires:
            - plan
